=== marwa9/VHV-Data-Decoding/Tag_list.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="ROOT">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="SECTION">
          <xs:complexType mixed="true">
            <xs:sequence minOccurs="0">
              <xs:element maxOccurs="unbounded" name="tag">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="tagid" type="xs:string" />
                    <xs:element name="Name" type="xs:string" />
                    <xs:element name="description" type="xs:string" />
                    <xs:element name="Length" type="xs:string" />
                    <xs:element name="Format" type="xs:string" />
                    <xs:element name="Flag" type="xs:unsignedByte" />
                    <xs:element minOccurs="0" maxOccurs="unbounded" name="item">
                      <xs:complexType>
                        <xs:attribute name="index" type="xs:unsignedByte" use="required" />
                        <xs:attribute name="information" type="xs:string" use="required" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="type" type="xs:string" use="optional" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required" />
            <xs:attribute name="id" type="xs:unsignedByte" use="required" />
            <xs:attribute name="description" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== marwa9/VHV-Data-Decoding/Tag_list.xml
<?xml version='1.0' encoding="UTF-8" ?>
<!-- 
 Date: 17 Aug 2016
 This xml file defines the list of tags used for EMV contact, contactless and retail development.
-->
<ROOT xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Tag_list.xsd">
  <SECTION name="EMV CONTACT" id ="0" description="list of tags used for EMV contact">
    <tag>
      <tagid>5F57</tagid>
      <Name>Account Type</Name>
      <description>Indicates the type of account selected on the terminal</description>
      <Length>1</Length>
      <Format>n 2</Format>
      <Flag>0</Flag>
    </tag>
    <tag>
      <tagid>9F01</tagid>
      <Name>Acquirer Identifier</Name>
      <description>Uniquely identifies the acquirer within each payment system</description>
      <Length>6</Length>
      <Format>n 6-11</Format>
      <Flag>0</Flag>
    </tag>
    <tag>
      <tagid>9F40</tagid>
      <Name>Additional Terminal Capabilities</Name>
      <description>Indicates the data input and output capabilities of the terminal</description>
      <Length>5</Length>
      <Format>b</Format>
      <Flag>1</Flag>
      <!-- Byte 1-->
      <item index="0" information="Cash"/>
      <item index="1" information="Goods"/>
      <item index="2" information="Services"/>
      <item index="3" information="Cashback"/>
      <item index="4" information="Inquiry"/>
      <item index="5" information="Transfer"/>
      <item index="6" information="Payment"/>
      <item index="7" information="Administrative"/>
	  <!-- Byte 2-->
      <item index="8" information="Cash Deposit"/>
      <item index="9" information="RFU"/>
      <item index="10" information="RFU"/>
      <item index="11" information="RFU"/>
      <item index="12" information="RFU"/>
      <item index="13" information="RFU"/>
      <item index="14" information="RFU"/>
      <item index="15" information="RFU"/>
	  <!-- Byte 3-->
      <item index="16" information="Numeric keys"/>
      <item index="17" information="Alphabetic and Special character keys"/>
      <item index="18" information="Command keys"/>
      <item index="19" information="Function keys"/>
      <item index="20" information="RFU"/>
      <item index="21" information="RFU"/>
      <item index="22" information="RFU"/>
      <item index="23" information="RFU"/>
	  <!-- Byte 4-->
      <item index="24" information="Print, attendant"/>
      <item index="25" information="Print, cardholder"/>
      <item index="26" information="Display, attendant"/>
      <item index="27" information="Display, cardholder"/>
      <item index="28" information="RFU"/>
      <item index="29" information="RFU"/>
      <item index="30" information="Code Table 10"/>
      <item index="31" information="Code Table 9"/>
	  <!-- Byte 5-->
      <item index="32" information="Code Table 8"/>
      <item index="33" information="Code Table 7"/>
      <item index="34" information="Code Table 6"/>
      <item index="35" information="Code Table 5"/>
      <item index="36" information="Code Table 4"/>
      <item index="27" information="Code Table 3"/>
      <item index="38" information="Code Table 2"/>
      <item index="39" information="Code Table 1"/>
    </tag>
    <tag>
      <tagid>81</tagid>
      <Name>Amount, Authorised (Binary)</Name>
      <description>Authorised amount of the transaction (excluding adjustments)</description>
      <Length>4</Length>
      <Format>b</Format>
      <Flag>0</Flag>
    </tag>
    <tag>
      <tagid>9F02</tagid>
      <Name>Amount, Authorised (Numeric)</Name>
      <description>Authorised amount of the transaction (excluding adjustments)</description>
      <Length>6</Length>
      <Format>n 12</Format>
      <Flag>0</Flag>
    </tag>
    <tag>
      <tagid>9F04</tagid>
      <Name>Amount, Other (Binary)</Name>
      <description>Secondary amount associated with the transaction representing a cashback amount</description>
      <Length>4</Length>
      <Format>b</Format>
      <Flag>0</Flag>
    </tag>
    <tag>
      <tagid>9F03</tagid>
      <Name>Amount, Other (Numeric)</Name>
      <description>Secondary amount associated with the transaction representing a cashback amount</description>
      <Length>6</Length>
      <Format>n 12</Format>
      <Flag>0</Flag>
    </tag>
    <tag>
      <tagid>9F3A</tagid>
      <Name>Amount, Reference Currency</Name>
      <description>Authorised amount expressed in the reference currency</description>
      <Length>4</Length>
      <Format>b</Format>
      <Flag>0</Flag>
    </tag>
    <tag>
      <tagid>9F26</tagid>
      <Name>Application Cryptogram</Name>
      <description>Cryptogram returned by the ICC in response of the GENERATE AC command</description>
      <Length>8</Length>
      <Format>b</Format>
      <Flag>0</Flag>
    </tag>
    <tag>
      <tagid>9F42</tagid>
      <Name>Application Currency Code</Name>
      <description>Indicates the currency in which the account is managed according to ISO 4217</description>
      <Length>2</Length>
      <Format>n 3</Format>
      <Flag>0</Flag>
    </tag>
    <tag>
      <tagid>9F44</tagid>
      <Name>Application Currency Exponent</Name>
      <description>Indicates the implied position of the decimal point from the right of the amount represented according to ISO 4217</description>
      <Length>1</Length>
      <Format>n 1</Format>
      <Flag>0</Flag>
    </tag>
    <tag>
      <tagid>9F05</tagid>
      <Name>Application Discretionary Data</Name>
      <description>Issuer or payment system specified data relating to the application</description>
      <Length>1-32</Length>
      <Format>b</Format>
      <Flag>0</Flag>
    </tag>
    <tag>
      <tagid>9F25</tagid>
      <Name>Application Effective Date</Name>
      <description>Date from which the application may be used</description>
      <Length>3</Length>
      <Format>n 6</Format>
      <Flag>0</Flag>
    </tag>
    <tag>
      <tagid>9F24</tagid>
      <Name>Application Expiration Date</Name>
      <description>Date after which application expires</description>
      <Length>3</Length>
      <Format>n 6</Format>
      <Flag>0</Flag>
    </tag>
    <tag>
      <tagid>94</tagid>
      <Name>Application File Locator (AFL)</Name>
      <description>Indicates the location (SFI, range of records) of the AEFs related to a given application</description>
      <Length>var. up to 252</Length>
      <Format>var.</Format>
      <Flag>0</Flag>
    </tag>
    <tag>
      <tagid>4F</tagid>
      <Name>Application Dedicated File (ADF) Name</Name>
      <description>Identifies the application as described in ISO/IEC 7816-5</description>
      <Length>5-16</Length>
      <Format>b</Format>
      <Flag>0</Flag>
    </tag>
    <tag>
      <tagid>9F06</tagid>
      <Name>Application Identifier (AID) terminal</Name>
      <description>Identifies the application as described in ISO/IEC 7816-5</description>
      <Length>5-16</Length>
      <Format>b</Format>
      <Flag>0</Flag>
    </tag>
    <tag>
      <tagid>82</tagid>
      <Name>Application Interchange Profile</Name>
      <description>Indicates the capabilities of the card to support specific functions in the application</description>
      <Length>2</Length>
      <Format>b</Format>
      <Flag>1</Flag>
	  <!-- Byte 1-->
	  <item index="0" information="RFU"/>
      <item index="1" information="SDA Supported"/>
      <item index="2" information="DDA Supported"/>
      <item index="3" information="Cardholder Verification is Supported"/>
      <item index="4" information="Terminal Risk Management is to be performed"/>
      <item index="5" information="Issuier Authentication is Supported"/>
      <item index="6" information="RFU"/>
      <item index="7" information="CDA Supported"/>
	  <!-- Byte 2-->
      <item index="8" information="RFU"/>
      <item index="9" information="RFU"/>
      <item index="10" information="RFU"/>
      <item index="11" information="RFU"/>
      <item index="12" information="RFU"/>
      <item index="13" information="RFU"/>
      <item index="14" information="RFU"/>
      <item index="15" information="RFU"/>
    </tag>
    <tag>
      <tagid>50</tagid>
      <Name>Application Label</Name>
      <description>Mnemonic associated with the AID according to ISO/IEC 7816-5</description>
      <Length>1-16</Length>
      <Format>ans with the special character limited to space</Format>
      <Flag>0</Flag>
    </tag>
    <tag>
      <tagid>9F12</tagid>
      <Name>Application Preferred Name</Name>
      <description>Preferred mnemonic associated with the AID</description>
      <Length>1-16</Length>
      <Format>ans (see section 4.3)</Format>
      <Flag>0</Flag>
    </tag>
    <tag>
      <tagid>5A</tagid>
      <Name>Application Primary Account Number (PAN)</Name>
      <description>Valid cardholder account number</description>
      <Length>var. up to 10</Length>
      <Format>cn var. up to 19</Format>
      <Flag>0</Flag>
    </tag>
    <tag>
      <tagid>5F34</tagid>
      <Name>Application Primary Account Number (PAN) Sequence Number</Name>
      <description>Identifies and differentiates cards with the same PAN</description>
      <Length>1</Length>
      <Format>n 2</Format>
      <Flag>0</Flag>
    </tag>
    <tag>
      <tagid>87</tagid>
      <Name>Application Priority Indicator</Name>
      <description>Indicates the priority of a given application or group of applications in a directory</description>
      <Length>1</Length>
      <Format>b</Format>
      <Flag>0</Flag>
    </tag>
    <tag>
      <tagid>9F3B</tagid>
      <Name>Application Reference Currency</Name>
